"""add renewal campaign tables

Revision ID: 460a7d7997d7
Revises: 9b8eb298dca3
Create Date: 2026-08-28 23:09:25.664570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460a7d7997d7'
down_revision: Union[str, Sequence[str], None] = '9b8eb298dca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renewal_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_campaigns_community_id'), 'renewal_campaigns', ['community_id'], unique=False)
    op.create_table('renewal_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', name='renewalconfirmationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['renewal_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'member_id', name='uq_renewal_confirmation')
    )
    op.create_index(op.f('ix_renewal_confirmations_campaign_id'), 'renewal_confirmations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_renewal_confirmations_member_id'), 'renewal_confirmations', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewal_confirmations_member_id'), table_name='renewal_confirmations')
    op.drop_index(op.f('ix_renewal_confirmations_campaign_id'), table_name='renewal_confirmations')
    op.drop_table('renewal_confirmations')
    op.drop_index(op.f('ix_renewal_campaigns_community_id'), table_name='renewal_campaigns')
    op.drop_table('renewal_campaigns')
    # ### end Alembic commands ###
