"""add reminder and decline fields to renewal confirmations

Revision ID: 46b43a119e27
Revises: a7c4d29e6f18
Create Date: 2026-08-31 16:00:04.437219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b43a119e27'
down_revision: Union[str, Sequence[str], None] = 'a7c4d29e6f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewal_confirmations', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('renewal_confirmations', sa.Column('reminder_message_id', sa.String(length=128), nullable=True))
    op.add_column('renewal_confirmations', sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renewal_confirmations', 'declined_at')
    op.drop_column('renewal_confirmations', 'reminder_message_id')
    op.drop_column('renewal_confirmations', 'reminder_sent_at')
    # ### end Alembic commands ###
