"""add archived_at to renewal_campaigns

Revision ID: 53f06bd899a1
Revises: 46b43a119e27
Create Date: 2026-08-31 18:04:27.180882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f06bd899a1'
down_revision: Union[str, Sequence[str], None] = '46b43a119e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewal_campaigns', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renewal_campaigns', 'archived_at')
    # ### end Alembic commands ###
