"""add group messages table

Revision ID: 81d358ae0dd8
Revises: 6dbbbec2a9d1
Create Date: 2026-08-31 22:26:21.616327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d358ae0dd8'
down_revision: Union[str, Sequence[str], None] = '6dbbbec2a9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('wa_message_id', sa.String(length=255), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'media', 'system', name='messagetype', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'wa_message_id', name='uq_group_message_wa_id')
    )
    op.create_index(op.f('ix_group_messages_group_id'), 'group_messages', ['group_id'], unique=False)
    op.create_index('ix_group_messages_group_sent_at', 'group_messages', ['group_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_group_messages_member_id'), 'group_messages', ['member_id'], unique=False)
    op.create_index(op.f('ix_group_messages_sent_at'), 'group_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_group_messages_wa_message_id'), 'group_messages', ['wa_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_messages_wa_message_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_sent_at'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_member_id'), table_name='group_messages')
    op.drop_index('ix_group_messages_group_sent_at', table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_group_id'), table_name='group_messages')
    op.drop_table('group_messages')
    # ### end Alembic commands ###
