"""add whatsapp otp two-factor auth

Revision ID: 888a09278a67
Revises: 81d358ae0dd8
Create Date: 2026-08-31 23:50:35.431226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888a09278a67'
down_revision: Union[str, Sequence[str], None] = '81d358ae0dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_wa_id', sa.String(length=128), nullable=True))
    # `server_default` required here (not just at the ORM level) — same
    # SQLite "can't add a NOT NULL column with no default to a populated
    # table" reasoning as `totp_enabled`'s own migration.
    op.add_column('users', sa.Column('whatsapp_otp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('pending_phone_wa_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('pending_otp_code_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pending_otp_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_otp_sent_at')
    op.drop_column('users', 'pending_otp_code_hash')
    op.drop_column('users', 'pending_phone_wa_id')
    op.drop_column('users', 'whatsapp_otp_enabled')
    op.drop_column('users', 'phone_wa_id')
    # ### end Alembic commands ###
