"""add growth snapshot tables

Revision ID: 9b8eb298dca3
Revises: 6fb2fa0b57b8
Create Date: 2026-08-28 22:41:08.518179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8eb298dca3'
down_revision: Union[str, Sequence[str], None] = '6fb2fa0b57b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_member_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('group_count', sa.Integer(), nullable=False),
    sa.Column('admin_count', sa.Integer(), nullable=False),
    sa.Column('pending_request_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_member_snapshots_community_id'), 'community_member_snapshots', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_member_snapshots_recorded_at'), 'community_member_snapshots', ['recorded_at'], unique=False)
    op.create_table('group_member_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('pending_request_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_member_snapshots_group_id'), 'group_member_snapshots', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_member_snapshots_recorded_at'), 'group_member_snapshots', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_member_snapshots_recorded_at'), table_name='group_member_snapshots')
    op.drop_index(op.f('ix_group_member_snapshots_group_id'), table_name='group_member_snapshots')
    op.drop_table('group_member_snapshots')
    op.drop_index(op.f('ix_community_member_snapshots_recorded_at'), table_name='community_member_snapshots')
    op.drop_index(op.f('ix_community_member_snapshots_community_id'), table_name='community_member_snapshots')
    op.drop_table('community_member_snapshots')
    # ### end Alembic commands ###
