"""add message-activity fields to group_memberships

Revision ID: c4151b849d4d
Revises: 460a7d7997d7
Create Date: 2026-08-30 13:44:09.574552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4151b849d4d'
down_revision: Union[str, Sequence[str], None] = '460a7d7997d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_memberships', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('group_memberships', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_memberships', 'last_seen_at')
    op.drop_column('group_memberships', 'last_message_at')
    # ### end Alembic commands ###
