"""add activity tracking fields to group_memberships

Revision ID: f3d8b1a2c9e7
Revises: c4151b849d4d
Create Date: 2026-08-30 14:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d8b1a2c9e7'
down_revision: Union[str, Sequence[str], None] = 'c4151b849d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'group_memberships',
        sa.Column(
            'last_activity_type',
            sa.Enum('message', 'reaction', 'view', name='activitytype', native_enum=False, length=16),
            nullable=True,
        ),
    )
    op.add_column('group_memberships', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('group_memberships', sa.Column('last_activity_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_memberships', 'last_activity_content')
    op.drop_column('group_memberships', 'last_activity_at')
    op.drop_column('group_memberships', 'last_activity_type')
    # ### end Alembic commands ###
